# Generated by Django 5.0.2 on 2024-02-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_age_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wattage', models.PositiveIntegerField(help_text='Watts consumed by the appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_watts_used', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='Energy cost in GBP', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts_used', models.PositiveIntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='api.appliance')),
                ('energy_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_usages', to='api.energyusage')),
            ],
        ),
    ]
