# Generated by Django 5.0.2 on 2024-03-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userconversationhistory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_setup',
            field=models.BooleanField(default=False),
        ),
    ]
